### ISSUE TITLE
Murphy SRCREV changed!

### ISSUE THREAD

**Issue by ExtremeGTX** [klihub/meta-murphy#1]
Hi
I think there was a rebase at [murphy repo](https://github.com/klihub/murphy) which changed the commit SHA.
I think the `SRCREV` correct value is [7d918fcc4ff5685115eda25eed9c6a934a7a427d](https://github.com/klihub/murphy/commit/7d918fcc4ff5685115eda25eed9c6a934a7a427d)

Thanks :)

**Comment by klihub** [comment]
Thanks ! I've updated SRCREV to point to that rebased commit.
Sorry about the rebase/me forgetting to update the meta layer.
